apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
  labels:
    app: wisecow
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: kirankumars/wisecowapp:latest
        ports:
        - containerPort: 4499
        volumeMounts:
        - name: tls-secret
          mountPath: /etc/ssl
          readOnly: true
      volumes:
      - name: tls-secret
        secret:
          secretName: wisecow-tls
---
apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  selector:
    app: wisecow
  ports:
  - protocol: TCP
    port: 443
    targetPort: 4499
  type: LoadBalancer
